[project]
name = "mutualfunds-prospectus-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "fastapi",
    "uvicorn",
    "requests",
    "docling",
    "docling-core",
    "pymupdf",
    "chromadb",
    "langchain",
    "langchain-core",
    "langchain-openai",
    "langchain-chroma",
    "openai",
    "transformers",
    "sentence-transformers",
    "pandas",
    "python-dateutil",
    "numpy",
    "onnxruntime<1.26",
    "pillow",
    "python-dotenv",
    "python-multipart",
    "pytz",
    "typing-extensions",
]
